POST http://127.0.0.1:8000/api/auth/register
Content-Type: application/json

{
  "name": "Saipul Doe",
  "email": "saipul@example.com",
  "password": "passwordku123",
  "password_confirmation": "passwordku123"
}

### LOGIN
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
  "email": "saipul@example.com",
  "password": "passwordku123"
}


### GET USER LOGIN
GET http://127.0.0.1:8000/api/auth/me
Authorization: Bearer ...

### LOGOUT
POST http://127.0.0.1:8000/api/auth/logout
Authorization: Bearer ...
